"""Remove unit

Revision ID: 1b85d1a4aef8
Revises: 42eca666db4d
Create Date: 2024-11-05 17:29:25.976440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b85d1a4aef8'
down_revision: Union[str, None] = '42eca666db4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_unit_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('unit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_unit_fkey', 'user', 'unit', ['unit'], ['id'])
    # ### end Alembic commands ###
